{
 "title": "Optimizer Hub dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gateway_version{$app_label=\"gateway\"},$cluster_label)"
    }
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "label_values(gateway_version{$cluster_label=\"$cluster\", $app_label=\"gateway\"},$namespace_label)"
    }
   },
   { "name": "quantile", "label": "Quantile", "query": "0.95" },
   { "name": "cluster_label", "query": "cluster" },
   { "name": "namespace_label", "query": "kubernetes_namespace" },
   { "name": "pod_label", "query": "kubernetes_pod_name" },
   { "name": "app_label", "query": "app" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VMs connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(clients_connected{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"})",
     "legendFormat": "VMs"
    }
   ]
  },
  {
   "title": "VM roundtrip time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by (le) (rate(gateway_queries_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__rate_interval])))",
     "legendFormat": "Q0.75"
    }
   ]
  },
  {
   "title": "Client JVMs by Feature Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cnc, rno, cs) (vms_connected{$cluster_label=\"$cluster\",$app_label=\"gateway\",$namespace_label=\"$ns\"})",
     "legendFormat": "CNC={{cnc}}, RNO={{rno}}, CS={{cs}}"
    }
   ]
  },
  {
   "title": "CPU usage by component",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_usage_seconds_total{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"[a-z].*\"}[$__range])) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_seconds_total{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"[a-z].*\"}[$__range])) by (container)",
     "legendFormat": "{{container}} [throttling]"
    }
   ]
  },
  {
   "title": "Server CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{$cluster_label=\"$cluster\",namespace=\"$ns\",container=\"\",pod=~\"(compile-broker|gateway|mgmt-gateway|cache|db|storage|operator|task-executor)-.*\"}[$__rate_interval]))",
     "legendFormat": "VCores used total"
    },
    {
     "expr": "sum(rate(compiler_process_cputime_seconds_sum{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "VCores used by compiler engine"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{$cluster_label=\"$cluster\",namespace=\"$ns\",resource=\"cpu\",pod=~\"compile-broker-.*\"}) * max(operator_scaling_replicas_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",appName=\"compile-broker\",kind=\"count\"})\n+\nmax(kube_pod_container_resource_requests{$cluster_label=\"$cluster\",namespace=\"$ns\",resource=\"cpu\",pod=~\"gateway-.*\"}) * max(operator_scaling_replicas_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",appName=\"gateway\",kind=\"count\"})\n+\nmax(kube_pod_container_resource_requests{$cluster_label=\"$cluster\",namespace=\"$ns\",resource=\"cpu\",pod=~\"cache-.*\"}) * max(operator_scaling_replicas_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",appName=\"cache\",kind=\"count\"})\n+\nsum(kube_pod_container_resource_requests{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",resource=\"cpu\",pod=~\"(mgmt-gateway|db|storage|operator|task-executor)-.*\"})",
     "legendFormat": "VCores requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{$cluster_label=\"$cluster\",namespace=\"$ns\",resource=\"cpu\",pod=~\"(compile-broker|gateway|mgmt-gateway|cache|db|storage|operator|task-executor)-.*\"} * on($cluster_label,namespace,pod) kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "VCores provided"
    }
   ]
  },
  {
   "title": "Server sizing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"compile-broker-.*\",phase=\"Running\"})",
     "legendFormat": "compile-broker"
    },
    {
     "expr": "sum(kube_pod_status_phase{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"gateway-.*\",phase=\"Running\"})",
     "legendFormat": "gateway"
    },
    {
     "expr": "sum(kube_pod_status_phase{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"cache-.*\",phase=\"Running\"})",
     "legendFormat": "cache"
    }
   ]
  },
  {
   "title": "Client JVMs",
   "type": "timeseries",
   "description": "The number of client VMs connected and their status",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(clients_connected{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"})",
     "legendFormat": "Total connected"
    },
    {
     "expr": "sum(vms_blocked_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"})",
     "legendFormat": "Backlogged"
    },
    {
     "expr": "sum(vms_local_fallback_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"})",
     "legendFormat": "Local fallback"
    }
   ]
  },
  {
   "title": "Time to start compilation",
   "type": "timeseries",
   "description": "the current absolute max waiting time for the compilation start (across all  VMs)",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(vms_max_compilation_waiting_time_local_queue{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"})",
     "legendFormat": "Maximum across all JVMs"
    },
    {
     "expr": "max(vms_max_compilation_waiting_time_cnc_queue{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"})",
     "legendFormat": "Maximum across all CNC"
    }
   ]
  },
  {
   "title": "Time to Clear Optimization Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(vms_blocked_max_time{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"})",
     "legendFormat": "Maximum across JVMs"
    }
   ]
  },
  {
   "title": "Compilations in progress",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(compilation_workers_active{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"})",
     "legendFormat": "Compilations"
    },
    {
     "expr": "sum(compilation_workers_parallelism{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"})",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Compilation requests incoming",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(incoming_substream_total{type=\"COMPILATIONREQUEST\",$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__rate_interval]))",
     "legendFormat": "Received by gateway"
    },
    {
     "expr": "sum(rate(compilations_dropped_total{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__rate_interval])) by (reason)",
     "legendFormat": "Dropped ({{reason}})"
    }
   ]
  },
  {
   "title": "Compilation Queues VMs / CNC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vms_local_compilations_waiting_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"})",
     "legendFormat": "VM"
    },
    {
     "expr": "sum(gateway_requestQueue{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}) + sum(compilation_queue_size{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"})",
     "legendFormat": "CNC"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 933 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{$cluster_label=\"$cluster\",namespace=\"$ns\"} > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Failed Pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 933 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_pod_status_phase{$cluster_label=\"$cluster\",namespace=\"$ns\",phase=\"Failed\"} > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Long Pod Startup",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 933 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "app_startup_seconds{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"} > 10",
       "legendFormat": "{{$pod_label}}"
      }
     ]
    },
    {
     "title": "Network Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 933 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_receive_errors_total{$cluster_label=\"$cluster\",namespace=\"$ns\"}[$__rate_interval])) > 0",
       "legendFormat": "{{pod}} receive errors"
      },
      {
       "expr": "sum by (pod) (rate(container_network_transmit_errors_total{$cluster_label=\"$cluster\",namespace=\"$ns\"}[$__rate_interval])) > 0",
       "legendFormat": "{{pod}} transmit errors"
      },
      {
       "expr": "sum by (pod) (rate(container_network_receive_packets_dropped_total{$cluster_label=\"$cluster\",namespace=\"$ns\"}[$__rate_interval])) > 0",
       "legendFormat": "{{pod}} receive dropped"
      },
      {
       "expr": "sum by (pod) (rate(container_network_transmit_packets_dropped_total{$cluster_label=\"$cluster\",namespace=\"$ns\"}[$__rate_interval])) > 0",
       "legendFormat": "{{pod}} transmit dropped"
      }
     ]
    },
    {
     "title": "Container Terminated Reason",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1879 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_pod_container_status_last_terminated_reason{$cluster_label=\"$cluster\",namespace=\"$ns\"} > 0",
       "legendFormat": "{{pod}} {{reason}}"
      }
     ]
    },
    {
     "title": "Pod Failure Reason",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1879 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_pod_status_reason{$cluster_label=\"$cluster\",namespace=\"$ns\"} > 0",
       "legendFormat": "{{pod}} {{reason}}"
      }
     ]
    },
    {
     "title": "Pending Hazelcast invocations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1879 },
     "targets": [
      {
       "expr": "hz_operations_pending_invocations{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}",
       "legendFormat": "{{$pod_label}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Native Compiler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compilations requests processed (success)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 934 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(compilations_complete_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",status=\"success\"}[$__rate_interval]))",
       "legendFormat": "Success"
      }
     ]
    },
    {
     "title": "Compilation requests processed (errors)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 934 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(compilations_complete_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",status!=\"success\"}[$__rate_interval])) by (status, reason)",
       "legendFormat": " {{status}} ({{reason}})"
      },
      {
       "expr": "sum(rate(compilations_dropped_total{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__rate_interval])) by (reason)",
       "legendFormat": "dropped ({{reason}})"
      }
     ]
    },
    {
     "title": "Compilation processing latency (success)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1131 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by (le, status, reason) (increase(compilations_complete_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",status=\"success\"}[$__rate_interval])))",
       "legendFormat": "Success Q$quantile"
      },
      {
       "expr": "max by (status, reason) (compilations_complete_seconds_max{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",status=\"success\"})",
       "legendFormat": "Success Max"
      }
     ]
    },
    {
     "title": "Compilation processing latency (errors)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1131 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by (le, status, reason) (increase(compilations_complete_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",status!=\"success\"}[$__rate_interval])))",
       "legendFormat": "{{status}} ({{reason}}) Q$quantile"
      },
      {
       "expr": "max by (status, reason) (compilations_complete_seconds_max{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",status!=\"success\"})",
       "legendFormat": "{{status}} ({{reason}}) Max"
      }
     ]
    },
    {
     "title": "gRPC calls (gateway->compile-broker, success)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1140 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(grpc_call_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\",method=\"azul.remotecompiler.compilebroker.api.CompilationDispatcher/Dispatch\",status=\"OK\"}[$__rate_interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "gRPC calls (gateway->compile-broker, errors)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1140 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(grpc_call_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\",method=\"azul.remotecompiler.compilebroker.api.CompilationDispatcher/Dispatch\",status!=\"OK\"}[$__rate_interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "VM State Cache latency histogram",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1180 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(vmstate_cache_get_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__rate_interval])))",
       "legendFormat": "Get Q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(vmstate_cache_put_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__rate_interval])))",
       "legendFormat": "Put Q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(vmstate_cache_invalidate_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__rate_interval])))",
       "legendFormat": "Invalidate Q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(vmstate_cache_cleanup_unknown_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__rate_interval])))",
       "legendFormat": "Cleanup Unknown Q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(vmstate_cache_getAll_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__rate_interval])))",
       "legendFormat": "GetAll Q$quantile"
      }
     ]
    },
    {
     "title": "VM state requests, latency histogram",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1180 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(vmstate_query_gw_seconds_bucket{$cluster_label=\"$cluster\",$app_label=\"compile-broker\",$namespace_label=\"$ns\",status=\"OK\"}[$__rate_interval])))",
       "legendFormat": "compile-broker->gateway (measured on compile-broker), Q$quantile OK"
      },
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(vmstate_query_gw_seconds_bucket{$cluster_label=\"$cluster\",$app_label=\"compile-broker\",$namespace_label=\"$ns\",status=\"ERROR\"}[$__rate_interval])))",
       "legendFormat": "compile-broker->gateway (measured on compile-broker), Q$quantile ERROR"
      },
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(vmstate_query_handler_seconds_bucket{$cluster_label=\"$cluster\",$app_label=\"gateway\",$namespace_label=\"$ns\", status=\"OK\"}[$__rate_interval])))",
       "legendFormat": "compile-broker->gateway (measured on gateway), Q$quantile OK"
      },
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(vmstate_query_handler_seconds_bucket{$cluster_label=\"$cluster\",$app_label=\"gateway\",$namespace_label=\"$ns\", status=\"ERROR\"}[$__rate_interval])))",
       "legendFormat": "compile-broker->gateway (measured on gateway), Q$quantile ERROR"
      },
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(gateway_queries_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\"}[$__rate_interval])))",
       "legendFormat": "gateway roundtrip to VM, Q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(compiler_vmstate_query_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__rate_interval])))",
       "legendFormat": "RCD->compile-broker (measured on compile-broker) Q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(gateway_to_vm_query_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\"}[$__rate_interval])))",
       "legendFormat": "gateway->VM (measured on VM), Q$quantile"
      }
     ]
    },
    {
     "title": "Match Rate ops/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1196 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(compilations_total{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__rate_interval])) by (cacheDetails)",
       "legendFormat": "{{cacheDetails}}"
      }
     ]
    },
    {
     "title": "Match failure reasons",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1204 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(codecache_mismatch_total{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__range])) by (mismatchDetail, msgName)",
       "legendFormat": "{{msgName}}-{{mismatchDetail}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ReadyNow Orchestrator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Profile download requests processed (success)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(storage_profile_download_duration_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason=\"success\"}[$__rate_interval]))",
       "legendFormat": "Success"
      }
     ]
    },
    {
     "title": "Profile download requests processed (errors)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (reason) (rate(storage_profile_download_duration_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason!=\"success\"}[$__rate_interval]))",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Profile download latency (success) [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(storage_profile_download_duration_seconds_sum{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason=\"success\"}[$__interval]))/\nsum(increase(storage_profile_download_duration_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason=\"success\"}[$__interval]))",
       "legendFormat": "Success Average"
      },
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(storage_profile_download_duration_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason=\"success\"}[$__interval])))",
       "legendFormat": "Success Q$quantile"
      },
      {
       "expr": "max(storage_profile_download_duration_seconds_max{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason=\"success\"})",
       "legendFormat": "Success Max"
      }
     ]
    },
    {
     "title": "Profile download latency (errors) [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(storage_profile_download_duration_seconds_sum{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason!=\"success\"}[$__interval])) by (reason)/\nsum(increase(storage_profile_download_duration_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason!=\"success\"}[$__interval])) by (reason)",
       "legendFormat": "{{reason}} Average"
      },
      {
       "expr": "histogram_quantile($quantile, sum by (reason, le) (increase(storage_profile_download_duration_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason!=\"success\"}[$__interval])))",
       "legendFormat": "{{reason}} Q$quantile"
      },
      {
       "expr": "max(storage_profile_download_duration_seconds_max{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason!=\"success\"}) by (reason)",
       "legendFormat": "{{reason}} Max"
      }
     ]
    },
    {
     "title": "Chunk upload latency (success) [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(storage_chunk_upload_duration_seconds_sum{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason=\"success\"}[$__interval]))/\nsum(increase(storage_chunk_upload_duration_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason=\"success\"}[$__interval]))",
       "legendFormat": "Success Average"
      },
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(storage_chunk_upload_duration_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason=\"success\"}[$__interval])))",
       "legendFormat": "Success Q$quantile"
      },
      {
       "expr": "max(storage_chunk_upload_duration_seconds_max{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason=\"success\"})",
       "legendFormat": "Success Max"
      }
     ]
    },
    {
     "title": "Chunk upload latency (errors) [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(storage_chunk_upload_duration_seconds_sum{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason!=\"success\"}[$__interval])) by (reason)/\nsum(increase(storage_chunk_upload_duration_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason!=\"success\"}[$__interval])) by (reason)",
       "legendFormat": "{{reason}} Average"
      },
      {
       "expr": "histogram_quantile($quantile, sum by (reason, le) (increase(storage_chunk_upload_duration_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason!=\"success\"}[$__interval])))",
       "legendFormat": "{{reason}} Q$quantile"
      },
      {
       "expr": "max(storage_chunk_upload_duration_seconds_max{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",reason!=\"success\"}) by (reason)",
       "legendFormat": "{{reason}} Max"
      }
     ]
    },
    {
     "title": "Indirect delivery snapshot",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum by (type) (rate(rno_snapshot_updates_total{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[1m])) * 60",
       "legendFormat": "{{outcome}}-{{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Profile Synchronization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Profile sync latency [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2908 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(opthub_synced_profiles_duration_seconds_sum{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__interval])) by (reason)",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Profile sync rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2908 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(opthub_synced_profiles_duration_seconds_count{$cluster_label=\"$cluster\", $namespace_label=\"$ns\"}[$__rate_interval])) by (reason)",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Number of synced profiles rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2924 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(opthub_synced_profiles_total{$cluster_label=\"$cluster\", $namespace_label=\"$ns\", $app_label=\"mgmt-gateway\"}[$__rate_interval])) by (reason)",
       "legendFormat": "{{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compilation Streaming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "GetStreamInfo (success)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(grpc_server_call_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\",method=\"azul.opthub.compstream.CompStreamService/GetStreamInfo\",status=\"OK\"}[$__rate_interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "GetStreamInfo (errors)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(grpc_server_call_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\",method=\"azul.opthub.compstream.CompStreamService/GetStreamInfo\",status!=\"OK\"}[$__rate_interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "GetStreamInfo latency (success)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(grpc_server_call_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\",method=\"azul.opthub.compstream.CompStreamService/GetStreamInfo\",status=\"OK\"}[$__rate_interval])))",
       "legendFormat": "Success Q$quantile"
      },
      {
       "expr": "max (grpc_server_call_seconds_max{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\",method=\"azul.opthub.compstream.CompStreamService/GetStreamInfo\",status=\"OK\"})",
       "legendFormat": "Success Max"
      }
     ]
    },
    {
     "title": "GetStreamInfo latency (errors)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by (status, le) (increase(grpc_server_call_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\",method=\"azul.opthub.compstream.CompStreamService/GetStreamInfo\",status!=\"OK\"}[$__rate_interval])))",
       "legendFormat": "{{status}} Q$quantile"
      },
      {
       "expr": "max by (status) (grpc_server_call_seconds_max{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\",method=\"azul.opthub.compstream.CompStreamService/GetStreamInfo\",status!=\"OK\"})",
       "legendFormat": "{{status}} Max"
      }
     ]
    },
    {
     "title": "GetStreamSegment (success)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(grpc_server_call_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\",method=\"azul.opthub.compstream.CompStreamService/GetStreamSegment\",status=\"OK\"}[$__rate_interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "GetStreamSegment (errors)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(grpc_server_call_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\",method=\"azul.opthub.compstream.CompStreamService/GetStreamSegment\",status!=\"OK\"}[$__rate_interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "GetStreamSegment latency (success)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(grpc_server_call_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\",method=\"azul.opthub.compstream.CompStreamService/GetStreamSegment\",status=\"OK\"}[$__rate_interval])))",
       "legendFormat": "Success Q$quantile"
      },
      {
       "expr": "max (grpc_server_call_seconds_max{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\",method=\"azul.opthub.compstream.CompStreamService/GetStreamSegment\",status=\"OK\"})",
       "legendFormat": "Success Max"
      }
     ]
    },
    {
     "title": "GetStreamSegment latency (errors)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by (status, le) (increase(grpc_server_call_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\",method=\"azul.opthub.compstream.CompStreamService/GetStreamSegment\",status!=\"OK\"}[$__rate_interval])))",
       "legendFormat": "{{status}} Q$quantile"
      },
      {
       "expr": "max by (status) (grpc_server_call_seconds_max{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\",method=\"azul.opthub.compstream.CompStreamService/GetStreamSegment\",status!=\"OK\"})",
       "legendFormat": "{{status}} Max"
      }
     ]
    },
    {
     "title": "Stream build (success)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(compstream_build_task_duration_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",status=\"success\"}[$__rate_interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Stream build (errors)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(compstream_build_task_duration_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",status!=\"success\"}[$__rate_interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Stream build latency (success)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by (le) (increase(compstream_build_task_duration_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",status=\"success\"}[$__rate_interval])))",
       "legendFormat": "Success Q$quantile"
      },
      {
       "expr": "max (compstream_build_task_duration_seconds_max{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",status=\"success\"})",
       "legendFormat": "Success Max"
      }
     ]
    },
    {
     "title": "Stream build latency (errors)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by (status, le) (increase(compstream_build_task_duration_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",status!=\"success\"}[$__rate_interval])))",
       "legendFormat": "{{status}} Q$quantile"
      },
      {
       "expr": "max by (status) (compstream_build_task_duration_seconds_max{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",status!=\"success\"})",
       "legendFormat": "{{status}} Max"
      }
     ]
    },
    {
     "title": "Compilations Waiting vs Expected Local",
     "type": "timeseries",
     "description": "Number of compilations expected to be served locally by JVMs (from compilation stream)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vms_local_compilations_waiting_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"})",
       "legendFormat": "Compilations waiting in client queues"
      },
      {
       "expr": "sum(vms_local_compilations_expected_local_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"})",
       "legendFormat": "Compilations expected to be served locally on JVM side"
      }
     ]
    },
    {
     "title": "Stream statistics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(compstream_jvm_installs_total{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__rate_interval]))",
       "legendFormat": "Installs"
      },
      {
       "expr": "sum(rate(compstream_jvm_lookups_total{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__rate_interval]))",
       "legendFormat": "Lookups"
      }
     ]
    },
    {
     "title": "Stream diagnostics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum by (reason) (rate(compstream_jvm_diagnostics_total{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}[$__rate_interval]))",
       "legendFormat": "{{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "External Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "mgmt-gateway REST API Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2928 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (method, uri, outcome) (rate(http_server_requests_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"mgmt-gateway\"}[$__rate_interval]))",
       "legendFormat": "{{method}} {{uri}} -> {{outcome}}"
      }
     ]
    },
    {
     "title": "mgmt-gateway REST API latency (success)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2928 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by (le, method, uri) (increase(http_server_requests_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"mgmt-gateway\", outcome=\"SUCCESS\"}[$__rate_interval])))",
       "legendFormat": "{{method}} {{uri}} Q$quantile"
      },
      {
       "expr": "max by (method, uri) (http_server_requests_seconds_max{$cluster_label=\"$cluster\",$namespace_label=\"$ns\", outcome=\"SUCCESS\"})",
       "legendFormat": "{{method}} {{uri}} Max"
      }
     ]
    },
    {
     "title": "mgmt-gateway REST API latency (failure)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2928 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by (le, method, uri, outcome) (increase(http_server_requests_seconds_bucket{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"mgmt-gateway\", outcome!=\"SUCCESS\"}[$__rate_interval])))",
       "legendFormat": "{{method}} {{uri}} -> {{outcome}} Q$quantile"
      },
      {
       "expr": "max by (method, uri, outcome) (http_server_requests_seconds_max{$cluster_label=\"$cluster\",$namespace_label=\"$ns\", outcome!=\"SUCCESS\"})",
       "legendFormat": "{{method}} {{uri}} -> {{outcome}} Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Details: compile-broker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per Pod Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1363 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"compile-broker-*\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"compile-broker-*\", resource=\"memory\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1371 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"compile-broker-.*\"}) by (phase)",
       "legendFormat": "{{phase}}"
      },
      {
       "expr": "sum(kube_pod_status_ready{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"compile-broker-.*\",condition=\"true\"})",
       "legendFormat": "Ready"
      },
      {
       "expr": "sum(operator_scaling_replicas_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",appName=\"compile-broker\",kind=\"count\"})",
       "legendFormat": "Requested by operator"
      }
     ]
    },
    {
     "title": "Per Pod CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1371 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"compile-broker-*\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"compile-broker-*\", resource=\"cpu\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Startup duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1378 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "app_startup_seconds{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"compile-broker\"}",
       "legendFormat": "{{$pod_label}}"
      }
     ]
    },
    {
     "title": "Container restarts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1378 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"compile-broker-.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod network traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1392 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"compile-broker-.*\"}[$__rate_interval]))",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"compile-broker-.*\"}[$__rate_interval]))",
       "legendFormat": "Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Details: cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2914 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"cache-.*\"}) by (phase)",
       "legendFormat": "{{phase}}"
      },
      {
       "expr": "sum(kube_pod_status_ready{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"cache-.*\",condition=\"true\"})",
       "legendFormat": "Ready"
      },
      {
       "expr": "sum(operator_scaling_replicas_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",appName=\"cache\",kind=\"count\"})",
       "legendFormat": "Requested by operator"
      }
     ]
    },
    {
     "title": "Per Pod CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2914 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"cache-*\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"cache-*\", resource=\"cpu\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Container restarts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2921 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"cache-.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Startup duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2921 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "app_startup_seconds{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"cache\"}",
       "legendFormat": "{{$pod_label}}"
      }
     ]
    },
    {
     "title": "Pod network traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2928 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"cache-.*\"}[$__rate_interval]))",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"cache-.*\"}[$__rate_interval]))",
       "legendFormat": "Transmit"
      }
     ]
    },
    {
     "title": "Per Pod Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2928 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "com_hazelcast_Metrics_usedHeap{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}",
       "legendFormat": "{{$pod_label}} - used heap"
      },
      {
       "expr": "com_hazelcast_Metrics_maxHeap{$cluster_label=\"$cluster\",$namespace_label=\"$ns\"}",
       "legendFormat": "{{$pod_label}} - max heap"
      },
      {
       "expr": "container_memory_usage_bytes{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"cache-*\"}",
       "legendFormat": "{{pod}} - used by container"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"cache*\", resource=\"memory\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Map Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2935 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(hz_stats_owned_cost{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"cache\"}) by (map)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Map Entry Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2935 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(hz_stats_owned_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"cache\"}) by (map)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Map Operation Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2942 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(hz_stats_latency_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"cache\"}[$__rate_interval])) by (map, operation)",
       "legendFormat": "{{map}}.{{operation}}"
      },
      {
       "expr": "sum(rate(hz_stats_operations_total{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"cache\"}[$__rate_interval])) by (map, operation)",
       "legendFormat": "{{map}}.{{operation}}"
      }
     ]
    },
    {
     "title": "Map Operation Average Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2942 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(hz_stats_latency_seconds_sum{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"cache\"}[$__rate_interval])) by (map, operation)/\nsum(increase(hz_stats_latency_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"cache\"}[$__rate_interval])) by (map, operation)",
       "legendFormat": "{{map}}.{{operation}}"
      }
     ]
    },
    {
     "title": "Hazelcast Migration Cycles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2950 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(hz_migration_elapsedTime_seconds_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"cache\"})",
       "legendFormat": "Completed"
      }
     ]
    },
    {
     "title": "Hazelcast Migration Cycle Elapsed Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2950 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(hz_migration_localTime_seconds_sum{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"cache\"})",
       "legendFormat": "Completed (on local instance)"
      }
     ]
    },
    {
     "title": "Hazelcast Partition Migrations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2958 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(hz_migrations_completed{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"cache\"})",
       "legendFormat": "Completed"
      },
      {
       "expr": "max(hz_migrations_planned{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"cache\"})",
       "legendFormat": "Planned"
      },
      {
       "expr": "max(hz_migrations_failed{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"cache\"})",
       "legendFormat": "Failed"
      }
     ]
    },
    {
     "title": "Hazelcast Dirty Entry",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2958 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hz_stats_dirtyentry{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"cache\"}",
       "legendFormat": "{{map}} - pod {{$pod_label}}"
      },
      {
       "expr": "sum(hz_stats_dirtyentry{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"cache\"})",
       "legendFormat": "All maps"
      }
     ]
    }
   ]
  },
  {
   "title": "Details: gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2781 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"gateway-.*\"}) by (phase)",
       "legendFormat": "{{phase}}"
      },
      {
       "expr": "sum(kube_pod_status_ready{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"gateway-.*\",condition=\"true\"})",
       "legendFormat": "Ready"
      },
      {
       "expr": "sum(operator_scaling_replicas_count{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",appName=\"gateway\",kind=\"count\"})",
       "legendFormat": "Requested by operator"
      }
     ]
    },
    {
     "title": "Per Pod CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2781 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"gateway-*\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"gateway-*\", resource=\"cpu\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Container restarts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2788 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"gateway-.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Startup duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2788 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "app_startup_seconds{$cluster_label=\"$cluster\",$namespace_label=\"$ns\",$app_label=\"gateway\"}",
       "legendFormat": "{{$pod_label}}"
      }
     ]
    },
    {
     "title": "Per Pod Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2795 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"gateway-*\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"gateway-*\", resource=\"memory\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Pod network traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2802 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"gateway-.*\"}[$__rate_interval]))",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"gateway-.*\"}[$__rate_interval]))",
       "legendFormat": "Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Details: task-executor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1598 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"task-executor-.*\"}) by (phase)",
       "legendFormat": "{{phase}}"
      },
      {
       "expr": "sum(kube_pod_status_ready{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"task-executor-.*\",condition=\"true\"})",
       "legendFormat": "Ready"
      }
     ]
    },
    {
     "title": "Per Pod CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1598 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"task-executor-*\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"task-executor-*\", resource=\"cpu\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Container restarts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1605 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"task-executor-.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Per Pod Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1605 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"task-executor-*\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"task-executor-*\", resource=\"memory\"})",
       "legendFormat": "Limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Detail: Envoy gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2569 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"gw-proxy-.*\"}) by (phase)",
       "legendFormat": "{{phase}}"
      },
      {
       "expr": "sum(kube_pod_status_ready{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"gw-proxy-.*\",condition=\"true\"})",
       "legendFormat": "Ready"
      }
     ]
    },
    {
     "title": "Per Pod CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2569 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"gw-proxy-*\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"gw-proxy-*\", resource=\"cpu\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Container restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2576 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{$cluster_label=\"$cluster\",namespace=\"$ns\",pod=~\"gw-proxy-.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Per Pod Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2576 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"gw-proxy-*\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{$cluster_label=\"$cluster\",namespace=\"$ns\",container=~\"gw-proxy-*\", resource=\"memory\"})",
       "legendFormat": "Limit"
      }
     ]
    }
   ]
  }
 ]
}