apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opthub-metrics-server
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - endpoints
      - pods
      - ingresses
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses/status
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server
  namespace: opthub
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opthub-metrics-server
subjects:
  - kind: ServiceAccount
    name: metrics-server
    namespace: opthub
roleRef:
  kind: ClusterRole
  name: opthub-metrics-server
  apiGroup: rbac.authorization.k8s.io
