---
###################################################################################################
# The rest of the settings are for reference only. You should not override any of these settings. #
###################################################################################################

simpleSizing:
  disabled: true

autoscaler: false

gateway:
  resources:

gwProxy:
  resources:

mgmtGateway:
  resources:

compileBroker:
  resources:

cache:
  resources:

db:
  resources:
    requests:
      cpu:
      memory:
      ephemeral-storage: "7Gi"
    limits:
      cpu:
      memory:
      ephemeral-storage: "7Gi"

operator:
  resources:


storage:
  blobStorageService: s3
  s3:
    commonBucket: opthub
    credentialsType: "static"
    storageEndpoint: http://minio.minio-dev.svc.cluster.local:9000

secrets:
  blobStorage:
    accesskey: minioadmin
    secretkey: minioadmin
