---
compileBroker:
  enabled: false
  replicas: 0

simpleSizing:
  disabled: true

compilations:
  parallelism:
    limitPerVm: 0
    limitPerCompileBroker: 0

codeCache:
  cleaner:
    enabled: false

operator:
  enabled: false
