---
compileBroker:
  enabled: false
  replicas: 0
  autoscaler:
    enabled: false
    max: 0

simpleSizing:
  disabled: true

compilations:
  parallelism:
    limitPerVm: 0
    limitPerCompileBroker: 0

codeCache:
  cleaner:
    enabled: false
