---
###################################################################################################
# The rest of the settings are for reference only. You should not override any of these settings. #
###################################################################################################

simpleSizing:
  disabled: true

autoscaler: false

gateway:
  resources:

gwProxy:
  resources:

mgmtGateway:
  enabled: false
  resources:

compileBroker:
  resources:

cache:
  resources:

operator:
  resources:


storage:
  blobStorageService: s3
  s3:
    commonBucket: opthub
    credentialsType: "static"
    storageEndpoint: http://minio.minio-dev.svc.cluster.local:9000

secrets:
  blobStorage:
    s3:
      accesskey: minioadmin
      secretkey: minioadmin
