{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-opthub-dashboard
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_dashboard: "1"
data:
  cnc_dashboard.json: |-
  {{ .Files.Get "config-files/grafana/opthub_dashboard.json" | nindent 4 }}
{{- end }}
