---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache
  namespace: {{ .Release.Namespace }}
  labels:
    app: cache
    {{- if .Values.cache.applicationLabels }}
    {{- .Values.cache.applicationLabels | toYaml | nindent 4 }}
    {{- end }}
  {{- if .Values.cache.applicationAnnotations }}
  annotations:
    {{- .Values.cache.applicationAnnotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.cache.replicas | default 1 }}
  podManagementPolicy: Parallel
  serviceName: cache
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
        {{- if .Values.cache.podTemplateLabels }}
        {{- .Values.cache.podTemplateLabels | toYaml | nindent 8 }}
        {{- end }}
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/q/metrics"
        prometheus.io/port: "8080"
        checksum/opthub.properties: {{ (include "opthub.properties.content" .) | sha256sum }}
        {{- if .Values.cache.podTemplateAnnotations }}
        {{- .Values.cache.podTemplateAnnotations | toYaml | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.cache.spec }}
      {{- .Values.cache.spec | toYaml | nindent 6 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 1001
      containers:
      - name: cache
        image: {{ .Values.registry.opthub }}/opthub-hazelcast:{{ default .Chart.AppVersion .Values.appVersionOverride }}{{ default .Values.versionSuffix .Values.cache.versionSuffix }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
        {{- if .Values.cache.command }}
        command: {{- .Values.cache.command | toYaml | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: 5701
          name: ch-server
        - containerPort: 8080
          name: metrics
        - containerPort: {{ .Values.cache.ports.internalGrpcPort }}
          name: grpc

{{- if ne true .Values.cache.disableKubernetesProbes }}
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: metrics
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: metrics
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /q/health/started
            port: metrics
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 10
{{- end }}

        env:
{{- if and (eq "s3" .Values.storage.blobStorageService) .Values.secrets.blobStorage.s3.secretkey .Values.secrets.blobStorage.s3.accesskey }}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ include "blobStorage.s3.secretName" . }}
                key: {{ .Values.secrets.blobStorage.s3.accessKeySecretKey }}
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "blobStorage.s3.secretName" . }}
                key: {{ .Values.secrets.blobStorage.s3.secretAccessKeySecretKey }}
{{- end }}
{{- if and (eq "azure-blob" .Values.storage.blobStorageService) (eq "sas-token" .Values.storage.azureBlob.authMethod) .Values.secrets.blobStorage.azure.sasToken }}
          - name: BLOB_STORAGE_AZURE_BLOB_SASTOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "azure.storage.secretName" . }}
                key: {{ .Values.secrets.blobStorage.azure.sasTokenSecretKey }}
{{- end }}
{{- if and (eq "azure-blob" .Values.storage.blobStorageService) (eq "connection-string" .Values.storage.azureBlob.authMethod) .Values.secrets.blobStorage.azure.connectionString }}
          - name: BLOB_STORAGE_AZURE_BLOB_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                name: {{ include "azure.storage.secretName" . }}
                key: {{ .Values.secrets.blobStorage.azure.connectionStringSecretKey }}
{{- end }}
        args:
          - "-XX:InitialRAMPercentage=80"
          - "-XX:MaxRAMPercentage=80"
          - "-XX:+ExitOnOutOfMemoryError"
          - "-XX:-OmitStackTraceInFastThrow"
{{- if .Values.cache.extraArguments }}
          {{- .Values.cache.extraArguments | toYaml | nindent 10 }}
{{- end }}
{{- if .Values.cache.extraArgumentsMap }}
    {{- range $key, $val := .Values.cache.extraArgumentsMap }}
          - -D{{ $key }}={{ $val }}
    {{- end }}
{{- end }}
        {{- if .Values.cache.resources }}
        resources: {{- .Values.cache.resources | toYaml | nindent 10 }}
        {{- end }}
        volumeMounts:
          - name: config
            mountPath: "/etc/opthub"
            readOnly: true
          - name: tmp-volume
            mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: quarkus-config
            items:
              - key: "opthub.properties"
                path: "opthub.properties"
        - name: tmp-volume
          emptyDir:
{{- if (((.Values.cache).resources).limits) }}
            sizeLimit: {{ get .Values.cache.resources.limits "ephemeral-storage" }}
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.cache.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "cache.serviceAccount" . }}
{{- if eq true .Values.cache.azureVirtualNodes }}
      nodeSelector:
        kubernetes.io/role: agent
        kubernetes.io/os: linux
        type: virtual-kubelet
{{- else if .Values.cache.nodeSelector }}
      nodeSelector: {{- .Values.cache.nodeSelector | toYaml | nindent 8 }}
{{- end }}
{{- if eq true .Values.cache.azureVirtualNodes }}
      tolerations:
        - key: virtual-kubelet.io/provider
          operator: Exists
        - key: azure.com/aci
          effect: NoSchedule
{{- else if .Values.cache.tolerations }}
      tolerations: {{- .Values.cache.tolerations | toYaml | nindent 8 }}
{{- end }}
{{- if and ( ne true .Values.gateway.azureVirtualNodes ) .Values.cache.affinity }}
      affinity: {{- .Values.cache.affinity | toYaml | nindent 8 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: {{ .Release.Namespace }}
  labels:
    app: cache
    {{- if .Values.cache.serviceLabels }}
    {{- .Values.cache.serviceLabels | toYaml | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5701
      protocol: TCP
      name: cache-server
  selector:
    app: cache

{{- if and (eq "" .Values.deployment.serviceAccount.existingServiceAccount) (eq "" .Values.cache.existingServiceAccount) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cache.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.deployment.serviceAccount.labels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.deployment.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opthub-cache-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - services
    verbs:
      - get
      - list


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opthub-cache-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opthub-cache-role
subjects:
  - kind: ServiceAccount
    name: {{ include "cache.serviceAccount" . }}
    namespace: {{ .Release.Namespace }}
