{{- if and (eq "" .Values.deployment.serviceAccount.existingServiceAccount) (eq "" .Values.compileBroker.existingServiceAccount)}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "compileBroker.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.deployment.serviceAccount.labels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.deployment.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if and .Values.compileBroker .Values.compileBroker.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compile-broker
  namespace: {{ .Release.Namespace }}
  labels:
    app: compile-broker
    {{- if .Values.compileBroker.applicationLabels }}
    {{- .Values.compileBroker.applicationLabels | toYaml | nindent 4 }}
    {{- end }}
  {{- if .Values.compileBroker.applicationAnnotations }}
  annotations:
    {{- .Values.compileBroker.applicationAnnotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ include "sizing.compileBroker.replicas" . }}
  selector:
    matchLabels:
      app: compile-broker
  template:
    metadata:
      labels:
        app: compile-broker
        {{- if .Values.compileBroker.podTemplateLabels }}
        {{- .Values.compileBroker.podTemplateLabels | toYaml | nindent 8 }}
        {{- end }}
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/q/metrics"
        {{- if .Values.compileBroker.podTemplateAnnotations }}
        {{- .Values.compileBroker.podTemplateAnnotations | toYaml | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.compileBroker.spec }}
      {{- .Values.compileBroker.spec | toYaml | nindent 6 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 1001
      containers:
      - name: compile-broker
        image: {{ .Values.registry.opthub }}/opthub-compile-broker:{{ default .Chart.AppVersion .Values.appVersionOverride }}{{ default .Values.versionSuffix .Values.compileBroker.versionSuffix }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
        {{- if .Values.compileBroker.command }}
        command: {{- .Values.compileBroker.command | toYaml | nindent 8 }}
        {{- end }}
        env:
          - name: DEFAULT_STORAGE_LOCATION_BUCKET
            value: {{ include "storageLocationBucket" . }}
          - name: DEFAULT_STORAGE_LOCATION_COMMON_PREFIX
            value: {{ include "storageLocationPathPrefixWithNamespace" . }}
{{- if eq "s3" .Values.storage.blobStorageService }}
          - name: BLOB_STORAGE_STORAGE_SERVICE
            value: s3
    {{- if eq "static" .Values.storage.s3.credentialsType }}
          - name: QUARKUS_S3_CLOUD_CREDENTIALS_STATIC_PROVIDER_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ include "blobStorage.s3.secretName" . }}
                key: {{ .Values.secrets.blobStorage.s3.accessKeySecretKey }}
          - name: QUARKUS_S3_CLOUD_CREDENTIALS_STATIC_PROVIDER_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "blobStorage.s3.secretName" . }}
                key: {{ .Values.secrets.blobStorage.s3.secretAccessKeySecretKey }}
          - name: QUARKUS_S3_CLOUD_CREDENTIALS_TYPE
            value: static
    {{- end }}
          - name: QUARKUS_S3_CLOUD_REGION
            value: {{ .Values.storage.s3.region }}
{{- else if eq "gcp-blob" .Values.storage.blobStorageService }}
          - name: BLOB_STORAGE_STORAGE_SERVICE
            value: gcp-blob
{{- else if eq "azure-blob" .Values.storage.blobStorageService }}
          - name: BLOB_STORAGE_STORAGE_SERVICE
            value: azure-blob
          - name: BLOB_STORAGE_AZURE_BLOB_ENDPOINT
            value: {{ .Values.storage.azureBlob.endpoint }}
          - name: BLOB_STORAGE_AZURE_BLOB_AUTHMETHOD
            value: {{ .Values.storage.azureBlob.authMethod }}
  {{- if and (eq "sas-token" .Values.storage.azureBlob.authMethod) .Values.secrets.blobStorage.azure.sasToken }}
          - name: BLOB_STORAGE_AZURE_BLOB_SASTOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "azure.storage.secretName" . }}
                key: {{ .Values.secrets.blobStorage.azure.sasTokenSecretKey }}
  {{- end }}
  {{- if and (eq "connection-string" .Values.storage.azureBlob.authMethod) .Values.secrets.blobStorage.azure.connectionString }}
          - name: BLOB_STORAGE_AZURE_BLOB_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                name: {{ include "azure.storage.secretName" . }}
                key: {{ .Values.secrets.blobStorage.azure.connectionStringSecretKey }}
  {{- end }}
{{- end }}
        args:
        - "-XX:+ExitOnOutOfMemoryError"
        - "-XX:MaxRAMPercentage=60"
        - "-XX:-OmitStackTraceInFastThrow"
        - "-Dquarkus.hazelcast-client.cluster-members=cache:5701"
        - "-Dgraceful.shutdown.timeout={{ max 0 (sub .Values.compileBroker.terminationGracePeriodSeconds 5) }}"
{{- if .Values.storage.s3.storageEndpoint }}
        - "-Dquarkus.s3.endpoint-override={{ .Values.storage.s3.storageEndpoint }}"
{{- end  }}
        - "-Dcompiler.parallelism={{ .Values.compilations.parallelism.limitPerCompileBroker }}"
        - "-Dcompiler.lookup-parallelism={{ .Values.compilations.parallelism.lookupParallelism }}"
{{- if .Values.compileBroker.extraArguments }}
        {{- .Values.compileBroker.extraArguments | toYaml | nindent 8 }}
{{- end }}
{{- if .Values.compileBroker.extraArgumentsMap }}
    {{- range $key, $val := .Values.compileBroker.extraArgumentsMap }}
        - -D{{ $key }}={{ $val }}
    {{- end }}
{{- end }}
        ports:
        - containerPort: 8080
          name: http-endpoint
        {{- if .Values.compileBroker.resources }}
        resources: {{- .Values.compileBroker.resources | toYaml | nindent 10 }}
        {{- end }}
        {{- if ne true .Values.compileBroker.disableKubernetesProbes }}
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: http-endpoint
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: http-endpoint
          initialDelaySeconds: 0
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /q/health/started
            port: http-endpoint
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 18
        {{- end }}
        volumeMounts:
          - name: tmp-volume
            mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir:
{{- if (((.Values.compileBroker).resources).limits) }}
            sizeLimit: {{ get .Values.compileBroker.resources.limits "ephemeral-storage" }}
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.compileBroker.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "compileBroker.serviceAccount" . }}
{{- if eq true .Values.compileBroker.azureVirtualNodes }}
      nodeSelector:
        kubernetes.io/role: agent
        kubernetes.io/os: linux
        type: virtual-kubelet
{{- else if .Values.compileBroker.nodeSelector }}
      nodeSelector: {{- .Values.compileBroker.nodeSelector | toYaml | nindent 8 }}
{{- end }}
{{- if eq true .Values.compileBroker.azureVirtualNodes }}
      tolerations:
        - key: virtual-kubelet.io/provider
          operator: Exists
        - key: azure.com/aci
          effect: NoSchedule
{{- else if .Values.compileBroker.tolerations }}
      tolerations: {{- .Values.compileBroker.tolerations | toYaml | nindent 8 }}
{{- end }}
{{- if and ( ne true .Values.compileBroker.azureVirtualNodes ) .Values.compileBroker.affinity }}
      affinity: {{- .Values.compileBroker.affinity | toYaml | nindent 8 }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: compile-broker
  namespace: {{ .Release.Namespace }}
  labels:
    app: compile-broker
    {{- if .Values.compileBroker.serviceLabels }}
    {{- .Values.compileBroker.serviceLabels | toYaml | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 50051
      protocol: TCP
      name: grpc-server
  selector:
    app: compile-broker
{{- end }}
