{{- include "validateRequiredValues" . }}

{{- if and (eq "" .Values.deployment.serviceAccount.existingServiceAccount) (eq "" .Values.gateway.existingServiceAccount)}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gateway.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.deployment.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: gateway
    {{- if .Values.gateway.applicationLabels }}
    {{- .Values.gateway.applicationLabels | toYaml | nindent 4 }}
    {{- end }}
  {{- if .Values.gateway.applicationAnnotations }}
  annotations:
    {{- .Values.gateway.applicationAnnotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.gateway.replicas | default 1 }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        {{- if .Values.gateway.podTemplateLabels }}
        {{- .Values.gateway.podTemplateLabels | toYaml | nindent 8 }}
        {{- end }}
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/q/metrics"
        checksum/opthub.properties: {{ (include "opthub.properties.content" .) | sha256sum }}
        {{- if .Values.gateway.podTemplateAnnotations }}
        {{- .Values.gateway.podTemplateAnnotations | toYaml | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 1001
      {{- if .Values.gateway.spec }}
      {{- .Values.gateway.spec | toYaml | nindent 6 }}
      {{- end }}
      containers:
      - name: gateway
        image: {{ .Values.registry.opthub }}/opthub-gateway:{{ default .Chart.AppVersion .Values.appVersionOverride }}{{ default .Values.versionSuffix .Values.gateway.versionSuffix }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
        {{- if .Values.gateway.command }}
        command: {{- .Values.gateway.command | toYaml | nindent 8 }}
        {{- end }}
        env:
{{- if and (eq "s3" .Values.storage.blobStorageService) .Values.secrets.blobStorage.s3.secretkey .Values.secrets.blobStorage.s3.accesskey }}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ include "blobStorage.s3.secretName" . }}
                key: {{ .Values.secrets.blobStorage.s3.accessKeySecretKey }}
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "blobStorage.s3.secretName" . }}
                key: {{ .Values.secrets.blobStorage.s3.secretAccessKeySecretKey }}
{{- end }}
{{- if and (eq "azure-blob" .Values.storage.blobStorageService) (eq "sas-token" .Values.storage.azureBlob.authMethod) .Values.secrets.blobStorage.azure.sasToken }}
          - name: BLOB_STORAGE_AZURE_BLOB_SASTOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "azure.storage.secretName" . }}
                key: {{ .Values.secrets.blobStorage.azure.sasTokenSecretKey }}
{{- end }}
{{- if and (eq "azure-blob" .Values.storage.blobStorageService) (eq "connection-string" .Values.storage.azureBlob.authMethod) .Values.secrets.blobStorage.azure.connectionString }}
          - name: BLOB_STORAGE_AZURE_BLOB_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                name: {{ include "azure.storage.secretName" . }}
                key: {{ .Values.secrets.blobStorage.azure.connectionStringSecretKey }}
{{- end }}
        args:
        - "-XX:+ExitOnOutOfMemoryError"
        - "-XX:MaxRAMPercentage=60"
        - "-XX:-OmitStackTraceInFastThrow"
{{- if .Values.gateway.extraArguments }}
        {{- .Values.gateway.extraArguments | toYaml | nindent 8 }}
{{- end }}
{{- if .Values.gateway.extraArgumentsMap }}
    {{- range $key, $val := .Values.gateway.extraArgumentsMap }}
        - -D{{ $key }}={{ $val }}
    {{- end }}
{{- end }}
        ports:
        - containerPort: 8080
          name: http-endpoint
        - containerPort: {{ .Values.gateway.ports.serviceGrpcPort }}
          name: grpc-external
{{- if .Values.gateway.resources }}
        resources: {{- .Values.gateway.resources | toYaml | nindent 10 }}
{{- end }}
        {{- if ne true .Values.gateway.disableKubernetesProbes }}
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: http-endpoint
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: http-endpoint
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /q/health/started
            port: http-endpoint
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 18
        {{- end }}
        volumeMounts:
          - name: config
            mountPath: "/etc/opthub"
            readOnly: true
          - name: tmp-volume
            mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: quarkus-config
            items:
              - key: "opthub.properties"
                path: "opthub.properties"
        - name: tmp-volume
          emptyDir:
{{- if (((.Values.gateway).resources).limits) }}
            sizeLimit: {{ get .Values.gateway.resources.limits "ephemeral-storage" }}
{{- end }}
      serviceAccountName: {{ include "gateway.serviceAccount" . }}
{{- if eq true .Values.gateway.azureVirtualNodes }}
      nodeSelector:
        kubernetes.io/role: agent
        kubernetes.io/os: linux
        type: virtual-kubelet
{{- else if .Values.gateway.nodeSelector }}
      nodeSelector: {{- .Values.gateway.nodeSelector | toYaml | nindent 8 }}
{{- end }}
{{- if eq true .Values.gateway.azureVirtualNodes }}
      tolerations:
        - key: virtual-kubelet.io/provider
          operator: Exists
        - key: azure.com/aci
          effect: NoSchedule
{{- else if .Values.gateway.tolerations }}
      tolerations: {{- .Values.gateway.tolerations | toYaml | nindent 8 }}
{{- end }}
{{- if and ( ne true .Values.gateway.azureVirtualNodes ) .Values.gateway.affinity }}
      affinity: {{- .Values.gateway.affinity | toYaml | nindent 8 }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: gateway
    {{- if .Values.gateway.serviceLabels }}
    {{- .Values.gateway.serviceLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.gateway.service.annotations }}
  annotations: {{- .Values.gateway.service.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  ports:
{{- if .Values.gateway.service.httpEndpoint.enabled }}
    - port: {{ .Values.gateway.service.httpEndpoint.port }}
      protocol: TCP
      name: http-server
      targetPort: 8080
{{- end }}
    - name: grpc-server
      protocol: TCP
      port: {{ .Values.gateway.service.grpc.port }}
      targetPort: {{ .Values.gateway.ports.serviceGrpcPort }}
{{- if  .Values.gwProxy.enabled }}
  selector:
    app: gw-proxy
  type: LoadBalancer
{{- else }}
  selector:
    app: gateway
  type: {{ .Values.gateway.service.type }}
{{- end }}
