{{- if and .Values.autoscaler .Values.compileBroker.autoscaler.enabled}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opthub-operator
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opthub-operator-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments/scale
      - deployments
      - statefulsets/scale
      - statefulsets
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opthub-operator-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: opthub-operator-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: opthub-operator
    namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: operator
    {{- if .Values.operator.applicationLabels }}
    {{- .Values.operator.applicationLabels | toYaml | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
        {{- if .Values.operator.podTemplateLabels }}
        {{- .Values.operator.podTemplateLabels | toYaml | nindent 8 }}
        {{- end }}
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8060"
        prometheus.io/path: "/q/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: operator
          image: {{ .Values.registry.opthub }}/opthub-operator:{{ .Values.version }}{{ .Values.operator.versionSuffix }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - -Dbroker.compilation-parallelism={{ .Values.compilations.parallelism.lookupParallelism }}
            - -Dbroker.min-replicas={{ include "sizing.compileBroker.minReplicas" . }}
            - -Dbroker.max-replicas={{ include "sizing.compileBroker.maxReplicas" . }}
            - -Dbroker.scale-down.stabilization-window=60s
            - -Dtime-to-clear-backlog={{ .Values.operator.timeToClearOptimizationBacklog}}
            - -Dsession-balancing.enabled={{ .Values.operator.sessionBalancing.enabled}}
{{- if eq "operator" .Values.cache.autoscaler.mode}}
            - -Dscaling.cache.enabled=true
            - -Dscaling.cache.min-replicas={{ include "sizing.cache.minReplicas" . }}
            - -Dscaling.cache.max-replicas={{ include "sizing.cache.maxReplicas" . }}
            - -Dscaling.cache.broker-instances-for-one={{ .Values.simpleSizing.relationships.brokersPerCache }}
{{- end }}
{{- if eq "operator" .Values.gateway.autoscaler.mode}}
            - -Dscaling.gateway.enabled=true
            - -Dscaling.gateway.min-replicas={{ include "sizing.gateway.minReplicas" . }}
            - -Dscaling.gateway.max-replicas={{ include "sizing.gateway.maxReplicas" . }}
            - -Dscaling.gateway.broker-instances-for-one={{ .Values.simpleSizing.relationships.brokersPerGateway }}
{{- end }}
{{- if .Values.operator.extraArguments }}
  {{- .Values.operator.extraArguments | toYaml | nindent 12 }}
{{- end }}
          {{- if .Values.operator.resources }}
          resources: {{- .Values.operator.resources | toYaml | nindent 12 }}
          {{- end }}
      serviceAccountName: opthub-operator
{{- if .Values.operator.nodeSelector }}
      nodeSelector: {{- .Values.operator.nodeSelector | toYaml | nindent 8 }}
{{- end }}
{{- if .Values.operator.tolerations }}
      tolerations: {{- .Values.operator.tolerations | toYaml | nindent 8 }}
{{- end }}
{{- end}}
