## Storage secrets
##    S3 static
{{- if and (eq "s3" .Values.storage.blobStorageService) (eq "static" .Values.storage.s3.credentialsType) (not .Values.secrets.blobStorage.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: blob-storage-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.secrets.blobStorage.s3.accessKeySecretKey }}: {{ .Values.secrets.blobStorage.s3.accesskey | b64enc }}
  {{ .Values.secrets.blobStorage.s3.secretAccessKeySecretKey }}: {{ .Values.secrets.blobStorage.s3.secretkey | b64enc }}
---
{{- end }}
##    end of S3 static

##    Azure connection string
{{- if and (eq "azure-blob" .Values.storage.blobStorageService) (ne "default-credentials" .Values.storage.azureBlob.authMethod) (not .Values.secrets.blobStorage.azure.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if and (eq "sas-token" .Values.storage.azureBlob.authMethod) .Values.secrets.blobStorage.azure.sasToken }}
  {{ .Values.secrets.blobStorage.azure.sasTokenSecretKey }}: {{ .Values.secrets.blobStorage.azure.sasToken | b64enc }}
  {{- end }}
  {{- if and (eq "connection-string" .Values.storage.azureBlob.authMethod) .Values.secrets.blobStorage.azure.connectionString }}
  {{ .Values.secrets.blobStorage.azure.connectionStringSecretKey }}: {{ .Values.secrets.blobStorage.azure.connectionString | b64enc }}
  {{- end }}
{{- end }}
##    end of Azure connection string

## SSL secrets
{{- if and .Values.ssl.enabled (not .Values.ssl.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-ssl-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cert.pem: |-
{{- if .Values.ssl.value.cert }}
    {{ .Values.ssl.value.cert | b64enc }}
{{- else }}
    {{ .Files.Get (printf "%s" .Values.ssl.path.cert) | b64enc }}
{{- end }}
  key.pem: |-
{{- if .Values.ssl.value.key }}
    {{ .Values.ssl.value.key | b64enc }}
{{- else }}
    {{ .Files.Get (printf "%s" .Values.ssl.path.key) | b64enc }}
{{- end }}
{{- if .Values.ssl.mtls.enabled }}
  client-truststore.p12: |-
    {{ .Files.Get (printf "%s" .Values.ssl.mtls.truststore) | b64enc }}
{{- end }}
---
{{- end }}
## end of SSL secrets
